### ISSUE TITLE
Is the URL supported forever?

### ISSUE THREAD

**Issue by phpstudyone** [Miljar/exiftool-docker#5]
First of all, thanks to the author for the work of docker install on exiftool, which makes exiftool more widely applicable.

However, the author obtains [exiftool source code](http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-${EXIFTOOL_VERSION}.tar.gz) code of exiftool from this URL for installation. Is this URL always safe and reliable, and can it be guaranteed that the source code can always be obtained from it?

**Comment by itsjavi** [comment]
@phpstudyone I'd rather use the official source files: 
`https://exiftool.org/Image-ExifTool-${EXIFTOOL_VERSION}.tar.gz`

**Comment by phpstudyone** [comment]
@itsjavi  Thank you, actually this really caused a problem with my service, until I changed to use the official source
